export const data = [
    { phrase: "I need to jump on another call", isChecked: false },
    { phrase: "You're on mute", isChecked: false },
    { phrase: "We lost you for a minute there", isChecked: false },
    { phrase: "Do we have everyone here?", isChecked: false },
    { phrase: "Can you see my screen?", isChecked: false },
    { phrase: "Can everyone mute themselves please?", isChecked: false },
    { phrase: "Let's take this offline", isChecked: false },
    { phrase: "I'm getting really bad feedback", isChecked: false },
    { phrase: "I've got a hard stop at __ o'clock", isChecked: false },
    { phrase: "Conscious there's only X minutes left", isChecked: false },
    { phrase: "Let's start the meeting", isChecked: false },
    { phrase: "Can you hear me?", isChecked: false },
    { phrase: "Turn your camera on", isChecked: false },
    { phrase: "Thanks everyone", isChecked: false },
    { phrase: "Lets wait 5 minutes", isChecked: false },
    { phrase: "Is someone eating chips?", isChecked: false },
    { phrase: "(Awkward Silence)", isChecked: false },
    { phrase: "Does that make sense?", isChecked: false },
    { phrase: "your voice is cutting off", isChecked: false },
    { phrase: "I think you are on mute", isChecked: false },
    { phrase: "Sorry about that, my pet is...", isChecked: false },
    { phrase: "(flush)", isChecked: false },
    { phrase: "Next slide, please", isChecked: false },
    { phrase: "Hello, hello...", isChecked: false },
  ];