export const data = [
  {
    phrase: "I need to jump on another call",
    isChecked: false,
    isBingo: false,
  },
  { phrase: "You're on mute", isChecked: false, isBingo: false },
  {
    phrase: "We lost you for a minute there",
    isChecked: false,
    isBingo: false,
  },
  { phrase: "Do we have everyone here?", isChecked: false, isBingo: false },
  { phrase: "Can you see my screen?", isChecked: false, isBingo: false },
  {
    phrase: "Can everyone mute themselves please?",
    isChecked: false,
    isBingo: false,
  },
  { phrase: "Let's take this offline", isChecked: false, isBingo: false },
  {
    phrase: "I'm getting really bad feedback",
    isChecked: false,
    isBingo: false,
  },
  {
    phrase: "I've got a hard stop at __ o'clock",
    isChecked: false,
    isBingo: false,
  },
  {
    phrase: "Conscious there's only X minutes left",
    isChecked: false,
    isBingo: false,
  },
  { phrase: "Let's start the meeting", isChecked: false, isBingo: false },
  { phrase: "Can you hear me?", isChecked: false, isBingo: false },
  { phrase: "Turn your camera on", isChecked: false, isBingo: false },
  { phrase: "Thanks everyone", isChecked: false, isBingo: false },
  { phrase: "Lets wait 5 minutes", isChecked: false, isBingo: false },
  { phrase: "Is someone eating chips?", isChecked: false, isBingo: false },
  { phrase: "(Awkward Silence)", isChecked: false, isBingo: false },
  { phrase: "Does that make sense?", isChecked: false, isBingo: false },
  { phrase: "your voice is cutting off", isChecked: false, isBingo: false },
  { phrase: "I think you are on mute", isChecked: false, isBingo: false },
  {
    phrase: "Sorry about that, my pet is...",
    isChecked: false,
    isBingo: false,
  },
  { phrase: "(flush)", isChecked: false, isBingo: false },
  { phrase: "Next slide, please", isChecked: false, isBingo: false },
  { phrase: "Hello, hello...", isChecked: false, isBingo: false },
];
